# Project: Australian Unemployed Prediction
### Description:

Goal: explore and clean the data 
Tech: Python\
Library: panda 
Data Source: Australian Bureau of Statistics

Data:\
All groups CPI, index numbers and percentage changes.xlsx

### Library:

In [6]:
# install
# !pip install pandas openpyxl

Collecting pandas
  Downloading pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata (18 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yuchi\anaconda3\envs\py38ver\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\yuchi\anaconda3\envs\py38ver\lib\site-packages (from pandas) (2026.1.post1)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting numpy>=1.20.3 (from pandas)
  Downloading numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata (5.6 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\yuchi\anaconda3\envs\py38ver\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
    --------------------------------------- 0.3/10.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.8 MB 2.2 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/10.8 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/10.8 MB 2.8 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/10.8 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/10.8 MB 2.9 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/10.8 MB 3.0 MB/s eta 0:00:03
   ------------------ --------------------- 5.0/10.8 MB 3.1 MB/s eta 0:00:02
   --------------------- ------------------ 5.8/10.8 MB 3.3 MB/s eta 0:00:02
   ------------------------- -------------- 6.8/10.8 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 7.6/10.8 MB 3.4 MB/s eta 0:00:01
   ------------------------------- -------- 8.4/10.8 MB 3.5 MB/s eta 0:00:01
   ---------------------------------- ----- 9.2/10.8 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/10.8 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 10.8/10.8 MB 3.6 MB/s eta 0:00:00
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/14.9 MB 9.4 MB/s eta 0:00:02
   --------- ------------------------------ 3.7/14.9 MB 9.9 MB/s eta 0:00:02
   --------------- ------------------------ 5.8/14.9 MB 10.1 MB/s eta 0:00:01
   -------------------- ------------------- 7.6/14.9 MB 9.8 MB/s eta 0:00:01
   ------------------------- -------------- 9.4/14.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------- ----------- 10.7/14.9 MB 9.6 MB/s eta 0:00:01
   ----------------------------------- ---- 13.1/14.9 MB 9.3 MB/s eta 0:00:01
   -------------------------------------- - 14.4/14.9 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 14.9/14.9 MB 8.7 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: tzdata, numpy, et-xmlfile, pandas, openpyxl
Successfully installed et-xmlfile-2.0.0 numpy-1.24.4 openpyxl-3.1.5 pandas-2.0.3 tzdata-2025.3

In [7]:
import pandas as pd

### Files:

In [14]:
fileLocation = "D:\Working Station\Career & Project\Data\laber prediction\Original Data"
CPI_Monthlypath = fileLocation + "\\" + "CPI_MonthlyPercentageChange.xlsx"

Read files

In [55]:
CPI_MonthlyOriginal = pd.read_excel(CPI_Monthlypath, sheet_name = "Data1")

### CPI_MonthlyPath

#### Observe and Analyse the dataset

In [115]:
CPI_MonthlyPath = CPI_MonthlyOriginal.copy()
CPI_MonthlyPath.head()

,Unnamed: 0,Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Cakes and biscuits ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Breakfast cereals ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Meat and seafoods ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Beef and veal ; Australia ;,...,Contribution to All groups CPI Percentage Points Change from Previous Period ; Education ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Preschool and primary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Secondary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Tertiary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance and financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Deposit and loan facilities (direct charges) ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other financial services ; Australia ;
0,Unit,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,...,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,...,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

Observation:\
Data set type - structural data, wide data sets
Size - 30rows X 133 columns
columns- first column contains the information of each rows without a column name which suppose to be the column names, including but not limited to Unit, series type, data type, etc. From the seconde column to the last column, the column name contains the industry, including all groups, non-alcoholic beverages, bread and cereal product, etc. 
Data types - the data sets contain categorical, numerical and datetime datasets

#### Data processing plan

First transform the data to the formate that is easy to work with before cleaning and wrangling the data set.\
Step1 - transfer the wide data to long.\
Step2 - extract the industries info and name the column industry.\
Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.\
Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.\
Setp5 - Check if Series ID is unique id for each CPI, if so use it as the primary key/index of the data set.\

#### Step1 - transfer the wide data to long.

In [116]:
CPT_Wide = CPI_MonthlyPath.T

#### Step2 - extract the industries info and name the column industry.

In [117]:
CPT_Wide.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,2024-05-01 00:00:00,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,-0.2307,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,0.0768,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,0.0015,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,-0.0013,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [118]:
CPT_Wide_resetIndex = CPT_Wide.reset_index()

In [119]:
CPT_Wide_resetIndex.head()

,index,0,1,2,3,4,5,6,7,8,...,20,21,22,23,24,25,26,27,28,29
0,Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
1,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
2,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
3,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
4,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [120]:
#make first row as column name
CPT_Wide_resetIndex.columns = CPT_Wide_resetIndex.iloc[0]
CPT_DropFirstRow = CPT_Wide_resetIndex.drop(0, axis = 0)

In [124]:
#name the first column industry
firstColumnName = CPT_DropFirstRow.columns[0]
rename = 'Industry'
CPT_rename = CPT_DropFirstRow.rename(columns = {firstColumnName:rename})

In [169]:
#reset index
CPT_Wide_resetIndex = CPT_rename.reset_index(drop=True)

In [171]:
#extract the industry
CPT_Wide_resetIndex['Industry'] = CPT_Wide_resetIndex['Industry'].str.split(' ; ', expand=True)[1]

#### Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.

In [177]:
CPT_Wide_resetIndex.columns[10:]

Index([2024-05-01 00:00:00, 2024-06-01 00:00:00, 2024-07-01 00:00:00,
       2024-08-01 00:00:00, 2024-09-01 00:00:00, 2024-10-01 00:00:00,
       2024-11-01 00:00:00, 2024-12-01 00:00:00, 2025-01-01 00:00:00,
       2025-02-01 00:00:00, 2025-03-01 00:00:00, 2025-04-01 00:00:00,
       2025-05-01 00:00:00, 2025-06-01 00:00:00, 2025-07-01 00:00:00,
       2025-08-01 00:00:00, 2025-09-01 00:00:00, 2025-10-01 00:00:00,
       2025-11-01 00:00:00, 2025-12-01 00:00:00, 2026-01-01 00:00:00],
      dtype='object', name=0)

In [180]:
CPT_Wide_resetIndex.iloc[:, 10:].head()

,2024-05-01,2024-06-01,2024-07-01,2024-08-01,2024-09-01,2024-10-01,2024-11-01,2024-12-01,2025-01-01,2025-02-01,...,2025-04-01,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-10-01,2025-11-01,2025-12-01,2026-01-01
0,-0.2307,0.3562,0.2612,-0.2834,0.0467,-0.2314,0.3761,0.6544,0.2766,0.0906,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
1,0.0768,-0.0238,0.1212,0.0355,-0.0846,0.0254,0.0524,0.0421,0.1427,-0.0225,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
2,0.0015,-0.0063,0.0139,-0.0003,-0.0018,0.0199,0.0053,0.0093,0.0113,-0.0192,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
3,-0.0013,0.0007,0.0017,-0.0017,-0.0017,0.0069,0.0049,0.0043,0.0016,-0.0014,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002
4,0.0022,-0.0044,0.0106,-0.001,-0.0013,0.017,-0.0014,-0.0031,0.0129,-0.0137,...,0,-0.0056,0.0015,0.0099,-0.0004,-0.0049,0.0006,0.0047,0.0022,0.0092

In [ ]:
CPT_melted_dateTime = pd.melt(CPT_Wide_resetIndex, id_vars=['dateTime'])

### Data Cleaning

Observation:\